### ISSUE TITLE
F-droid

### ISSUE THREAD

**Issue by testman42** [rmst/yoke-android#1]
Since Yoke is FOSS; would you be so kind and make it available on [F-droid](https://f-droid.org/en/)?

**Comment by testman42** [comment]
Oh, I see you already answered [here](https://github.com/rmst/yoke/issues/3). Awesome :+1:

**Comment by jaller94** [comment]
Yoke 0.1.1 got released on F-Droid yesterday.

**Comment by rmst** [comment]
Great thank you!
