### ISSUE TITLE
Is a newer update available?

### ISSUE THREAD

**Issue by LamprosPitsillos** [rmst/yoke-android#12]
From what I can see the commits are quite active but the latest version is the one from 2018. Could you please build a newer version and push it to the stores? Or provide some instructions on how to build it ourself?
Thank you very much!

**Comment by JingMatrix** [comment]
You can learn how to build from the official documentations:
https://developer.android.com/studio/build/building-cmdline .

Also, my fork has minor updates:
https://github.com/JingMatrix/yoke-android .

**Comment by rmst** [comment]
@LamprosPitsillos this project suffers from the https://en.wikipedia.org/wiki/Second-system_effect. We tried to add a lot more features in the second version and then ran out of steam.

If you just need accelerometer control and two joysticks the "classic" version should just work fine. You can follow the instructions https://github.com/rmst/yoke and use the app store version of the app.

**Comment by rmst** [comment]
But to answer the titular question: No there isn't a properly working newer update available as far as I know.
