### ISSUE TITLE
frustrated

### ISSUE THREAD

**Issue by hacky10111** [rmst/yoke-android#13]
worst app ever.....
maybe you should give some better instructions in your README file...

**Comment by JingMatrix** [comment]
See my fork, hope it helps:

https://github.com/JingMatrix/yoke-android

**Comment by rmst** [comment]
@hacky10111 Did you try to follow the instructions for the "classic" version at https://github.com/rmst/yoke and used the app store version of the app? Please re-open if this doesn't work for you.
