### ISSUE TITLE
[minor] Hide navigation bar

### ISSUE THREAD

**Issue by medape** [rmst/yoke-android#4]
I couldn't figure the code for these on my own. I'd need to keep track of many Android good practices and intefaces.

My device is configured to use a navigation bar instead of Back, Menu and Overview hard keys. In these devices, this navigation bar isn't hidden in the Yoke webview; see the black strip at right hand:

![softkeys](https://user-images.githubusercontent.com/47781797/56097130-f6a16100-5edf-11e9-96f9-2bc0bda212c8.png)

(In my case, I enabled the navigation bar editing `props.build`, but some devices don't have these hard keys at all. Do you have easy access to one of them, to check?)

This means that some screen estate is wasted, and it's easy to exit the app by accident. This is especially frustrating because as soon as you open some other map, the controller disconnects from the web server.

**Comment by rmst** [comment]
This shouldn't be happening. In the android_manifest there should be an option like full screen or something to hide this navigation bar (it can be recovered by swiping from the screen edge).

**Comment by medape** [comment]
That helped a lot, indirectly. Thank you.

I searched yesterday through StackOverflow and Google Documentation for help with the Android Manifest, but I couldn't find anything conclusive. Apparently, Google makes a distinction between navigation bar, title bar, status bar, and other toolbars, and I couldn't find a way to have the navigation bar always hidden through the manifest.

But I found a code snippet in Google Documentation that almost solved the problem, and I'm learning how to use it. For the moment, I have this on `onResume()`:

```
getWindow().getDecorView().setSystemUiVisibility(
    View.SYSTEM_UI_FLAG_LAYOUT_STABLE
    | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
    | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
    | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
    | View.SYSTEM_UI_FLAG_IMMERSIVE);
```

As soon as I iron out some glitches (like the action bar reappearing when opening the last connections menu), I'll upload a new commit and close this issue.

**Comment by medape** [comment]
Fixed in commit [`5428cc`](https://github.com/medape/yoke-android/commit/5428ccaad2bf6dce6659fd7520089a1737206159). I'll try to fix a couple things more (hopefully, [issue #39 for the HTML code among them](https://github.com/rmst/yoke/issues/39)) before making a pull request.
