### ISSUE TITLE
Button presence

### ISSUE THREAD

**Issue by galou** [rmst/yoke-android#6]
Hi, thanks for the nice application!

I didn't manage to have buttons working. Are they linked to hardware buttons on the phone?

I need a button for ROS which using one button as enable-switch. Do you know any mean to have a button working.

Thanks,
Gaël

**Comment by medape** [comment]
By ROS, do you mean [this](https://en.wikipedia.org/wiki/Robot_Operating_System)?

For the moment, Yoke is only controlled with the touchscreen and motion controls. Hardware buttons do nothing yet.

The default gamepad layouts can emulate buttons in the touchscreen, but they're regular spring buttons (hold down for ON, release finger for OFF). Switches (touch it once to leave it ON, again to leave it OFF) aren't supported yet, but I'll be happy to implement them.

**Comment by galou** [comment]
Yes, this is the ROS I meant. Sorry that I forgot the link.

Regular spring buttons are actually what I would need (though the lazy side of me says that switches would allow me to release my finger).

You speak about a default layout. Does it mean that other layouts are possible?

Thanks!

**Comment by medape** [comment]
Yes, they're possible. We just didn't get around to documenting them yet.

...and I just have realized you're probably using the classic version. If the screen in your phone is all blue like in the GIF (https://github.com/rmst/yoke)[in the main page], **your version is outdated**. If that's the case, I'll try to upload proper instructions in a couple of days.

If the background of your app is white, you're using one of the new versions, but we've just rolled updates a couple days ago, so I recommend you download the latest version anyways, in both your PC and in your phone. 

To install, simply run **(thanks, @pzmarzly. The wrong command was here)**

```
git clone --depth 1 https://github.com/rmst/yoke
pip3 install yoke/
```

Once you're done, you'll find the most current APK at `yoke/devel/app-debug.apk`.

**Comment by pzmarzly** [comment]
> Once you're done, you'll find the most current APK

Well, not if you clone `--branch v0.1` :smile: . Try:

```bash
git clone --depth 1 https://github.com/rmst/yoke
cd yoke
pip3 install .
```

**Comment by medape** [comment]
A draft for the full instructions can be read at [medape/yoke/WEBVIEW.md](https://github.com/medape/yoke/blob/master/WEBVIEW.md). Please ask any question or add any suggestion at rmst/yoke#43.

**Comment by galou** [comment]
Indeed, I proceeded according to the instructions in `README.md` and checked-out `v0.1`. I'll give a try to the newest version as I find time.
