### ISSUE TITLE
[minor] Hide the progress bar when there is no update in progress

### ISSUE THREAD

**Issue by pzmarzly** [rmst/yoke-android#7]
The gray bar could be hidden by default, and shown only when files are being transmitted. @medape

![Screenshot_20191025-160550](https://user-images.githubusercontent.com/8074163/67577972-cfa2d200-f741-11e9-93f3-c696e3f7f101.png)

**Comment by medape** [comment]
Good idea. Hiding it should be easy - I'll get to it when I can and make sure it looks good, too. (I'd rather avoid the gamepad area from resizing while the progress bar is hidden.)
